//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogrenci.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class akademik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public akademik()
        {
            this.ders = new HashSet<ders>();
        }
    
        public string pkod { get; set; }
        public string sicilno { get; set; }
        public string padi { get; set; }
        public string psoyadi { get; set; }
        public string bransi { get; set; }
        public string bolumu { get; set; }
        public string ptc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ders> ders { get; set; }
    }
}
