//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogrenci.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class bolumler
    {
        public string bkod { get; set; }
        public string badi { get; set; }
        public string bbsk { get; set; }
        public byte bkon { get; set; }
    }
}
