//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogrenci.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ders()
        {
            this.notlar = new HashSet<notlar>();
            this.akademik = new HashSet<akademik>();
        }
    
        public string dkod { get; set; }
        public string dadi { get; set; }
        public byte dteo { get; set; }
        public byte duyg { get; set; }
        public byte dakts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notlar> notlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<akademik> akademik { get; set; }
    }
}
