//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogrenci.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class notlar
    {
        public string ogrno { get; set; }
        public string dkod { get; set; }
        public byte vize { get; set; }
        public byte final { get; set; }
        public string ddurum { get; set; }
    
        public virtual ders ders { get; set; }
        public virtual ogrenci ogrenci { get; set; }
    }
}
