//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogrenci.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ogrenci()
        {
            this.notlar = new HashSet<notlar>();
        }
    
        public string ogrno { get; set; }
        public string ogradi { get; set; }
        public string ogrsoyadi { get; set; }
        public string ogradres { get; set; }
        public string ogrbolumu { get; set; }
        public Nullable<bool> ogrcins { get; set; }
        public string ogrtcno { get; set; }
        public Nullable<System.DateTime> ogrdogumtar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notlar> notlar { get; set; }
    }
}
